parserOptions:
  ecmaVersion: 6
  project: ./tsconfig.json

env:
  node: true

extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended

rules:
  import/prefer-default-export: off
  lines-between-class-members:
    - error
    - always
    - { exceptAfterSingleLine: true }
  import/order:
    - error
    - { newlines-between: always }
